eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/anchunming/spring-cloud-test.git
            search-paths: config-repo
            username: 13836012043@163.com
            password: 15146714083asbet


#spring.application.name=config-server
#server.port=8888

#spring.cloud.config.server.git.uri=https://github.com/anchunming/spring-cloud-test.git
#spring.cloud.config.server.git.searchPaths=respo
#spring.cloud.config.label=master
#spring.cloud.config.server.git.username=1308218493@qq.com
#spring.cloud.config.server.git.password=15146714083asbet
